name: gseba
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.0
  permission_handler: ^11.0.1
  webview_flutter: ^4.5.0
  webview_flutter_android: ^3.16.0
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.2
  http: ^1.1.0
  flutter_downloader: ^1.11.6
  open_file: ^3.3.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/

